# Generated by Django 2.2.11 on 2021-04-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20201121_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieParseHistory',
        ),
        migrations.AddField(
            model_name='movieusercomment',
            name='calculated_label_emotion',
            field=models.SmallIntegerField(choices=[('POSITIVE', 1), ('NEUTRAL', 0), ('NEGATIVE', -1)], null=True),
        ),
        migrations.AddField(
            model_name='movieusercomment',
            name='expected_label_emotion',
            field=models.SmallIntegerField(choices=[('POSITIVE', 1), ('NEUTRAL', 0), ('NEGATIVE', -1)], null=True),
        ),
    ]
