# Generated by Django 2.2.11 on 2021-05-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20210428_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieusercomment',
            name='purified_body',
            field=models.TextField(null=True),
        ),
    ]
