# Generated by Django 2.2.11 on 2021-06-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_movieusercomment_purified_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128)),
                ('emotion', models.SmallIntegerField(choices=[('POSITIVE', 1), ('NEUTRAL', 0), ('NEGATIVE', -1)])),
                ('part', models.SmallIntegerField(choices=[('NOUN', 0), ('ADVERB', 1), ('ADJECTIVE', 2), ('VERB', 3)])),
            ],
        ),
    ]
